from os.path import expanduser, isfile

N_THREADS = 8

def get_sample_ids(fname):
    ret = []
    with open(fname, 'r') as fhandle:
        for line in fhandle:
            ret.append(line.strip("\n"))
    return ret

META = 'metadata/hiseq_accession.txt'
HOME = expanduser("~")

SRA_SINGLE = []
if isfile(META):
    SRA_SINGLE = get_sample_ids(META)

ANNO_PRE = "annotation/Saccharomyces_cerevisiae.R64-1-1.rel81.cdna.all"
ANNO_FA = ANNO_PRE + ".fa.gz"
KAL_IDX = ANNO_PRE + ".kidx"

rule all:
    input:
        META,
        expand('results/single/{id}/kallisto/abundance.h5', id = SRA_SINGLE)

rule get_transcriptome:
    output: ANNO_FA
    shell:
        'wget -O {ANNO_FA} http://bio.math.berkeley.edu/kallisto/transcriptomes/Saccharomyces_cerevisiae.R64-1-1.rel81.cdna.all.fa.gz'

rule kallisto_index:
    input: ANNO_FA
    output: KAL_IDX
    threads: 1
    shell:
        'kallisto index -k 21 -i {KAL_IDX} ' + ANNO_FA

rule fastq_dump_single:
    output:
        'data/single/{id}',
        'data/single/{id}/{id}.fastq.gz',
    benchmark:
        'benchmarks/{id}/fastq_dump.json'
    threads: 1
    shell:
        'fastq-dump '
        '-O {output[0]} '
        '--gzip '
        '{wildcards.id}'

rule kallisto_single:
    input:
        'data/single/{id}/{id}.fastq.gz',
        KAL_IDX
    output:
        'results/single/{id}/kallisto',
        'results/single/{id}/kallisto/abundance.h5'
    threads: 1
    shell:
        'kallisto quant '
        '-i {KAL_IDX} '
        '-b 100 '
        '--single '
        '-l 200 '
        '-s 30 '
        '--bias '
        '-t 7 '
        '-o {output[0]} '
        '{input[0]}'
