from os.path import expanduser, isfile

N_THREADS = 8

def get_sample_ids(fname):
    ret = []
    with open(fname, 'r') as fhandle:
        for line in fhandle:
            ret.append(line.strip("\n"))
    return ret

META = 'metadata/accessions.txt'
HOME = expanduser("~")

SRA_SINGLE = []
if isfile(META):
    SRA_SINGLE = get_sample_ids(META)

ANNO_PRE = "Saccharomyces_cerevisiae.R64-1-1.dna.toplevel"
ANNO_FA = ANNO_PRE + ".fa.gz"
KAL_IDX = ANNO_PRE + ".kidx"
GTF = 'Saccharomyces_cerevisiae.R64-1-1.80.gtf'

ensembl = 'ftp://ftp.ensembl.org/pub/release-80'

rule all:
    input:
        META,
        expand('results/single/{id}/kallisto/abundance.h5', id = SRA_SINGLE)

rule get_transcriptome:
    output:
        expand('../genome/{f}', f = ANNO_FA)
    shell:
        'cd ../genome && '
        'wget -O {ANNO_FA}.gz {ensembl}/fasta/saccharomyces_cerevisiae/dna/Saccharomyces_cerevisiae.R64-1-1.dna.toplevel.fa.gz && '
        'gunzip {ANNO_FA}.gz'

rule get_anno:
    input:
        expand('../genome/{f}', f = ANNO_FA)
    output:
        expand('../annotation/{g}', g = GTF)
    shell:
        'cd ../annotation && '
        'wget -O {GTF}.gz {ensembl}/gtf/saccharomyces_cerevisiae/Saccharomyces_cerevisiae.R64-1-1.80.gtf.gz && '
        'gunzip {GTF}.gz && '
        'gffread {GTF} ../genome/{ANNO_FA}'

rule kallisto_index:
    input:
        expand('../genome/{f}', f = ANNO_FA)
    output: KAL_IDX
    threads: 1
    shell:
        'kallisto index -k 21 -i {KAL_IDX} ../genome/{ANNO_FA}'

rule fastq_dump_single:
    output:
        'data/single/{id}',
        'data/single/{id}/{id}.fastq.gz',
    benchmark:
        'benchmarks/{id}/fastq_dump.json'
    threads: 1
    shell:
        'fastq-dump '
        '-O {output[0]} '
        '--gzip '
        '{wildcards.id}'

rule kallisto_single:
    input:
        'data/single/{id}/{id}.fastq.gz',
        KAL_IDX
    output:
        'results/single/{id}/kallisto',
        'results/single/{id}/kallisto/abundance.h5'
    threads: 1
    shell:
        'kallisto quant '
        '-i {KAL_IDX} '
        '-b 100 '
        '--single '
        '-l 200 '
        '-s 30 '
        '--bias '
        '-t 8 '
        '-o {output[0]} '
        '{input[0]}'
