fasta = 'Rattus_norvegicus.Rnor_5.0.rel79.cdna.all.fa.gz'
kidx = 'Rattus_norvegicus.Rnor_5.0.rel79.cdna.all.kidx'

sample_ids = ['HKS1A', 'HKS2A', 'HKS3B', 'LKS1A', 'LKS2A', 'LKS3B']

rule all:
	input:
		kidx, 
		expand('results/{sample}/kallisto/abundance.h5', sample = sample_ids)
	output:
		'sharma.rds'
	shell:
		'Rscript sharma_run.R'

rule get_transcriptome:
	output:
		fasta
	shell:
		'wget -O {fasta} http://bio.math.berkeley.edu/kallisto/transcriptomes/Rattus_norvegicus.Rnor_5.0.rel79.cdna.all.fa.gz'

rule index:
	input:
		fasta
	output:
		kidx
	shell:
		'kallisto index -k 21 -i {output} {fasta}'

rule kallisto: 
	input: 
		'results/{sample}/Sharma-RNA-{sample}_1.txt.gz',
		kidx
	output:
		'results/{sample}/kallisto',
		'results/{sample}/kallisto/abundance.h5'
	threads: 10
	shell: 
		'kallisto quant '
		'-i {kidx} '
		'--bias '
		'-b 100 '
		'-o {output[0]} '
		'-t {threads} '
		'--single '
		'-l 180 ' #these numbers (estimate mean and estimate standard deviation)
		'-s 20 '  #are completely made up. TODO: get an actual estimate
		'{input[0]} '

rule clean:
	shell:
		'rm -rf results/*/kallisto {kidx}'
