library(devtools)
library(sleuth)
source("http://bioconductor.org/biocLite.R")
biocLite("biomaRt")

mart <- biomaRt::useMart(biomart = "ensembl", dataset = "hsapiens_gene_ensembl")
t2g <- biomaRt::getBM(attributes = c("ensembl_transcript_id", "ensembl_gene_id", "external_gene_name"), mart = mart)
t2g <- dplyr::rename(t2g, target_id = ensembl_transcript_id, ens_gene = ensembl_gene_id, ext_gene = external_gene_name)
base_dir <- "/Users/lpachter/tmp/Ng_10.1016_j.stem.2015.08.003"
sample_id <- dir(file.path(base_dir,"results/paired"))
kal_dirs <- rev(sapply(sample_id, function(id) file.path(base_dir, "results/paired", id, "kallisto")))
s2c <- read.table(file.path(base_dir,"SraRunTable.txt"), header = TRUE, stringsAsFactors=FALSE)
s2c <- dplyr::select(s2c, sample = run, condition)
so <- sleuth_prep(kal_dirs, s2c, ~ condition, target_mapping = t2g)
so <- sleuth_fit(so)
so <- sleuth_test(so, which_beta = 'conditionsmn')
sleuth_live(so)