from os.path import expanduser, isfile

N_THREADS = 8

def get_sample_ids(fname):
    ret = []
    with open(fname, 'r') as fhandle:
        for line in fhandle:
            ret.append(line.strip("\n"))
    return ret

META = 'metadata/SRR_Acc_List.txt'
HOME = expanduser("~")

SRA_PAIRED = []
if isfile(META):
    SRA_PAIRED = get_sample_ids(META)

ANNO_PRE = "Latimeria_chalumnae.LatCha1.dna.toplevel"
ANNO_FA = ANNO_PRE + ".fa"
KAL_IDX = ANNO_PRE + ".kidx"
GTF = "Latimeria_chalumnae.LatCha1.80.gtf"

ensembl = 'ftp://ftp.ensembl.org/pub/release-80'

rule all:
    input:
        META,
        expand('results/paired/{id}/kallisto/abundance.h5', id = SRA_PAIRED)

rule get_transcriptome:
    output:
        expand('../genome/{f}', f = ANNO_FA)
    shell:
        'cd ../genome && '
        'wget -O {ANNO_FA}.gz {ensembl}/fasta/latimeria_chalumnae/dna/Latimeria_chalumnae.LatCha1.dna.toplevel.fa.gz && '
        'gunzip {ANNO_FA}.gz'

rule get_anno:
    input:
        expand('../genome/{f}', f = ANNO_FA)
    output:
        expand('../annotation/{g}', g = GTF)
    shell:
        'cd ../annotation && '
        'wget -O {GTF}.gz {ensembl}/gtf/latimeria_chalumnae/Latimeria_chalumnae.LatCha1.80.gtf.gz && '
        'gunzip {GTf}.gz && '
	    'gffread {GTF} ../genome/{ANNO_FA}'

rule kallisto_index:
    input:
        expand('../genome/{f}', f = ANNO_FA)
    output: KAL_IDX
    threads: 1
    shell:
        'kallisto index -k 21 -i {KAL_IDX} ../genome/{ANNO_FA}'

rule fastq_dump_paired:
    output:
        'data/paired/{id}',
        'data/paired/{id}/{id}_1.fastq.gz',
        'data/paired/{id}/{id}_2.fastq.gz'
    benchmark:
        'benchmarks/{id}/fastq_dump.json'
    threads: 1
    shell:
        'fastq-dump '
        '--split-files '
        '-O {output[0]} '
        '--gzip '
        '{wildcards.id}'

rule kallisto_paired:
    input:
        'data/paired/{id}/{id}_1.fastq.gz',
        'data/paired/{id}/{id}_2.fastq.gz',
        KAL_IDX
    output:
        'results/paired/{id}/kallisto',
        'results/paired/{id}/kallisto/abundance.h5'
    threads: 1
    shell:
        'kallisto quant '
        '-i {KAL_IDX} '
        '-b 100 '
        '-t 8 '
        '-o {output[0]} '
        '{input[0]} {input[1]}'
