fasta = 'Saccharomyces_cerevisiae.R64-1-1.rel81.cdna.all.fa.gz'
kidx = 'Saccharomyces_cerevisiae.R64-1-1.rel81.cdna.all.21.kidx'

sids = ['SRR1812768', 'SRR1812760', 'SRR1811834', 'SRR1812754', 'SRR1812759',
        'SRR1812767']

rule all:
    input:
        kidx,
        expand('results/{s}/kallisto/abundance.h5', s = sids)

rule index:
    output:
        kidx
    shell:
        'kallisto index '
        '-k 21 '
        '-i {output} '
        '{fasta}'

rule kallisto:
    input:
        'results/{samp}/{samp}_1.fastq.gz',
        'results/{samp}/{samp}_2.fastq.gz',
        kidx
    output:
        'results/{samp}/kallisto',
        'results/{samp}/kallisto/abundance.h5'
    threads: 2
    shell:
        'kallisto '
        'quant '
        '-i {kidx} '
        '--bias '
        '-b 30 '
        '-o {output[0]} '
        '-t {threads} '
        '{input[0]} {input[1]}'

rule clean:
    shell:
        'rm -rf results/*/kallisto {kidx}'
